version: "2"
services:
  movie-recommender:
    build:
      context: .
      dockerfile: Dockerfile.movie-recommender
    image: movie-recommender:latest
    network_mode: bridge
    entrypoint:
      - /bin/entrypoint.sh
    ports:
      - "5001:5001"
