apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: movie-recommender
    name: movie-recommender
  spec:
    ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
    selector:
      io.kompose.service: movie-recommender
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: movie-recommender
    name: movie-recommender
  spec:
    replicas: 1
    selector:
      io.kompose.service: movie-recommender
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: movie-recommender
      spec:
        containers:
        - command:
          - /bin/entrypoint.sh
          env:
          - name: SERVICE_TIMEOUT
            value: "900"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: access-key-id
          - name: AWS_BUCKET
            value: movie-reco-model
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: secret-access-key
          - name: DEPLOYMENT_PREFIX
            value: DEV
          - name: SERVICE_PORT
            value: "5001"
          image: ' '
          name: movie-recommender
          ports:
          - containerPort: 5001
          resources: {}
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - movie-recommender
        from:
          kind: ImageStreamTag
          name: movie-recommender:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: movie-recommender
    name: movie-recommender
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: movie-recommender
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: movie-recommender:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: .
      git:
        ref: master
        uri: git@github.com:harjinder-hari/cloud_native_analytics.git
      sourceSecret:
        name: "kattappasecret"
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile.movie-recommender
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}

